### ISSUE TITLE
tracks.get_Priority does not exist

### ISSUE THREAD

**Issue by MikeDMorgan** [MikeDMorgan/CGATViewer#1]
When calling the Layout.generatePlot() function it checks the priority of the track object.  However, Track objects do not have a priority attribute.  This priority can be hard-coded for now, or have it passed by the user from the config file.

**Comment by Charlie-George** [comment]
Updated tracks class to include methods to get_Priority() and set_Priority(), tracks now have two more attributes "priority" and "name" setting that can be predefined by user in config file - currently set to default values input of "default" in track class.
